# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartpole.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61rtpole.proto\"I\n\x08\x43\x61rtPole\x12\x0c\n\x04wait\x18\x01 \x01(\r\x12\x0e\n\x06inputs\x18\x04 \x03(\x01\x12\x0f\n\x07outputs\x18\x06 \x03(\x01\x12\x0e\n\x06reward\x18\x07 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cartpole_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CARTPOLE']._serialized_start=18
  _globals['_CARTPOLE']._serialized_end=91
# @@protoc_insertion_point(module_scope)
